title: Metamorfose dos Pássaros
description: >- # this means to ignore newlines until "baseurl:"
  Página oficial do filme Metamorfose dos Pássaros de Catarina Vasconcelos.
# the subpath of your site, e.g. /blog
url: "http://metamorfosedospassaros.pt" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
permalink: pretty 
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
